In [1]:
#importing pytorch module which will be used in this project!!
import torch
import  torch.nn as nn
import pandas as pd
import sklearn
from torch.utils.data import DataLoader,Dataset

# Note:- pytorch mei explicity softmax layer as actiavtion output layer mei mentioned nahi karna hota kyu ki jo loss function CrossEntropyLoss woh implicity softmax se probabilty nikalte hai

In [2]:
#now checking cuda or gpu is available in my system or not
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device

device(type='cuda')

In [3]:
#now loading the dataset by using pandas library
data = pd.read_csv("fmnist_small.csv")
data.head()

label  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0      9       0       0       0       0       0       0       0       0   
1      7       0       0       0       0       0       0       0       0   
2      0       0       0       0       0       0       1       0       0   
3      8       0       0       0       0       0       0       0       0   
4      8       0       0       0       0       0       0       0       0   

   pixel9  ...  pixel775  pixel776  pixel777  pixel778  pixel779  pixel780  \
0       0  ...         0         7         0        50       205       196   
1       0  ...         0         0         0         0         0         0   
2       0  ...       142       142       142        21         0         3   
3       0  ...         0         0         0         0         0         0   
4       0  ...       213       203       174       151       188        10   

   pixel781  pixel782  pixel783  pixel784  
0       213       165         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [4]:
#now checking label output having how many classes exist in it!!
data.label.unique()

array([9, 7, 0, 8, 1, 4, 2, 6, 5, 3])

In [5]:
data.label.value_counts()

label
6    656
7    620
5    612
2    604
4    595
0    595
3    591
1    590
8    582
9    555
Name: count, dtype: int64

In [6]:
data.duplicated().sum()

np.int64(1)

In [7]:
#Dropping those duplicates record
data.drop_duplicates(inplace=True)

In [8]:
#selecting input and output variable
x = data.drop(columns=['label'],axis=1)
y = data['label']

In [9]:
#splitting the dataset into train test split
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42,stratify=y)


In [10]:
type(x_train)

pandas.core.frame.DataFrame

In [11]:
#now performing input scaling by using min,max scaling
x_train = x_train/255.0
x_test = x_test/255.0


In [12]:
x_train

pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
3725     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
3562     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
1322     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
3018     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
1930     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
...      ...     ...     ...     ...     ...     ...     ...     ...   
1292     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
2361     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
4926     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
3192     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
2298     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

        pixel9   pixel10  ...  pixel775  pixel776  pixel777  pixel778  \
3725  0.000000  0.000000  ...  0.537255  0.286275  0.000000  0.000000   
3562  0.423529  0.047059  ...  0.352941  0.356863  0.329412  0.000000   
1322  0.000000  0.258824  ...  0.000000  0.094118  0.000000  0.011765   
3018  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
1930  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
...        ...       ...  ...       ...       ...       ...       ...   
1292  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
2361  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
4926  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
3192  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
2298  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   

      pixel779  pixel780  pixel781  pixel782  pixel783  pixel784  
3725       0.0       0.0       0.0       0.0       0.0       0.0  
3562       0.0       0.0       0.0       0.0       0.0       0.0  
1322       0.0       0.0       0.0       0.0       0.0       0.0  
3018       0.0       0.0       0.0       0.0       0.0       0.0  
1930       0.0       0.0       0.0       0.0       0.0       0.0  
...        ...       ...       ...       ...       ...       ...  
1292       0.0       0.0       0.0       0.0       0.0       0.0  
2361       0.0       0.0       0.0       0.0       0.0       0.0  
4926       0.0       0.0       0.0       0.0       0.0       0.0  
3192       0.0       0.0       0.0       0.0       0.0       0.0  
2298       0.0       0.0       0.0       0.0       0.0       0.0  

[4799 rows x 784 columns]

# now changing thise training and testing set to numpy array object

In [13]:
import numpy as np

In [14]:
x_train = np.array(x_train,dtype=np.float32)
x_test = np.array(x_test,dtype=np.float32)
y_train = np.array(y_train,dtype=np.int64)
y_test = np.array(y_test,dtype=np.int64)

In [15]:
x_train.ndim,x_train.dtype

(2, dtype('float32'))

# now changing this numpy object to tensor object

In [16]:
x_train = torch.from_numpy(x_train)
x_test = torch.from_numpy(x_test)
y_train = torch.from_numpy(y_train)
y_test = torch.from_numpy(y_test)

In [17]:
y_train = y_train.long()   # Convert float to long (because we have to change if we have multi class output)
y_test = y_test.long()


In [18]:
x_train.dtype,x_train.shape

(torch.float32, torch.Size([4799, 784]))

In [19]:
x_train

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

# now creating dataloader object by using custom dataset class

In [20]:
#In this class we define feature and label and also showing shape and returning based on index feature and label
class CustomDataset(Dataset): 
    #in this class we used 3 special or magical method
    def __init__(self,feature,label):
        super().__init__()
        self.feature = feature
        self.label = label
        
    def __len__(self):
        return len(self.feature)
    
    def __getitem__(self, index):
        return self.feature[index],self.label[index]
        

In [21]:
#creating an object of CustomDataset class
training_dataset = CustomDataset(x_train,y_train)
testing_dataset = CustomDataset(x_test,y_test)

In [22]:
#now creating the object of DataLoader class
train_dataloader =   DataLoader(training_dataset,batch_size=10,shuffle=True,pin_memory=True)
testing_dataloader = DataLoader(testing_dataset,batch_size=10,shuffle=False,pin_memory=True)

# creating a custom neural network architecture inheriting parent class property Module

In [23]:
class BasicArchitecture(nn.Module):
    #using constructor method for initializing the trainable parameter(weights and bias)
    def __init__(self,input_feature):
        
        super().__init__()
        
        #defining trainable parameter of first layer
        self.linear1 = nn.Linear(input_feature,128)
        self.relu1 = nn.ReLU()
        
        #defining 2nd layer of trainable parameter
        self.linear2 = nn.Linear(128,64)
        self.relu2 = nn.ReLU()
        
        #defining 3rd layer of trainable parameter
        self.linear3 = nn.Linear(64,10)
        
        
    #defining the forward propogation algorithm!!
    def forward(self,input_feature):
        #output of first second and third layer
        output = self.relu1(self.linear1(input_feature))
        output = self.relu2(self.linear2(output))
        output = self.linear3(output)
        
        return output

In [24]:
x_train.shape[1]

784

In [25]:
#creating an object of BasicArchitecture class
model = BasicArchitecture(input_feature=x_train.shape[1]).to(device)
model

BasicArchitecture(
  (linear1): Linear(in_features=784, out_features=128, bias=True)
  (relu1): ReLU()
  (linear2): Linear(in_features=128, out_features=64, bias=True)
  (relu2): ReLU()
  (linear3): Linear(in_features=64, out_features=10, bias=True)
)

In [26]:
#if i want to see the summary of the model
from torchinfo import summary
summary(model)

Layer (type:depth-idx)                   Param #
BasicArchitecture                        --
├─Linear: 1-1                            100,480
├─ReLU: 1-2                              --
├─Linear: 1-3                            8,256
├─ReLU: 1-4                              --
├─Linear: 1-5                            650
Total params: 109,386
Trainable params: 109,386
Non-trainable params: 0

In [27]:
#now defining the optimizers or compiling model 
lr = 0.01
epochs = 50

optimizer = torch.optim.Adam(model.parameters(),lr=lr) 
#optimizer will reduce the loss gradulally and helping to reach to global minima point
optimizer

Adam (
Parameter Group 0
    amsgrad: False
    betas: (0.9, 0.999)
    capturable: False
    decoupled_weight_decay: False
    differentiable: False
    eps: 1e-08
    foreach: None
    fused: None
    lr: 0.01
    maximize: False
    weight_decay: 0
)

In [28]:
for feature,label in train_dataloader:
    
    print(feature)
    print(label)

tensor([[0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        ...,
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0039, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000]])
tensor([8, 0, 2, 8, 3, 0, 3, 3, 6, 0])
tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])
tensor([1, 4, 7, 0, 1, 6, 1, 4, 9, 3])
tensor([[0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0039, 0.0000, 0.0000],
        ...,
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
 

In [29]:
loss_function = nn.CrossEntropyLoss() #this will calculate loss for sparse categorical cross entropy

In [30]:
#want to see what will be initialize wts and bias in each layer
model.linear1.weight

Parameter containing:
tensor([[-0.0137, -0.0297,  0.0273,  ...,  0.0199, -0.0268, -0.0194],
        [ 0.0104,  0.0267,  0.0354,  ..., -0.0354,  0.0204, -0.0138],
        [-0.0029,  0.0233, -0.0314,  ..., -0.0329, -0.0021, -0.0116],
        ...,
        [ 0.0284, -0.0100,  0.0064,  ..., -0.0332, -0.0078, -0.0349],
        [-0.0149,  0.0126,  0.0352,  ..., -0.0315,  0.0128,  0.0010],
        [-0.0316,  0.0341, -0.0356,  ..., -0.0167, -0.0019, -0.0215]],
       device='cuda:0', requires_grad=True)

In [31]:
model.linear1.bias

Parameter containing:
tensor([-0.0238, -0.0194, -0.0073, -0.0026,  0.0257,  0.0220, -0.0351, -0.0340,
        -0.0170,  0.0230,  0.0238, -0.0031, -0.0172, -0.0001, -0.0137,  0.0301,
         0.0120, -0.0244, -0.0176, -0.0060, -0.0122, -0.0003, -0.0238,  0.0213,
        -0.0117,  0.0061, -0.0143, -0.0100,  0.0089, -0.0045, -0.0126, -0.0321,
        -0.0132, -0.0290,  0.0257,  0.0064,  0.0134, -0.0293,  0.0151, -0.0121,
         0.0353,  0.0253, -0.0113, -0.0008,  0.0202, -0.0143, -0.0290,  0.0257,
        -0.0117, -0.0293,  0.0021, -0.0023, -0.0260, -0.0040,  0.0018, -0.0251,
         0.0062, -0.0250, -0.0307,  0.0282, -0.0150,  0.0240, -0.0354, -0.0301,
         0.0322,  0.0317, -0.0344,  0.0275, -0.0350, -0.0019, -0.0050, -0.0072,
        -0.0213, -0.0328, -0.0336, -0.0130,  0.0108, -0.0094,  0.0151, -0.0318,
         0.0105, -0.0102,  0.0086,  0.0093,  0.0113, -0.0052,  0.0121, -0.0136,
        -0.0210, -0.0058, -0.0084, -0.0056, -0.0224, -0.0121,  0.0020, -0.0210,
         0.0018, -

In [32]:
'''
| Use Case                | Data                     | Tensor Type    |
| ----------------------- | ------------------------ | -------------- |
| Features/Input          | Continuous values        | `float32`      |
| Predictions (logits)    | Output from model        | `float32`      |
| Labels (classification) | Class index (e.g. 0,1,2) | `long` (int64) |
| Labels (regression)     | Real value (e.g. 4.5)    | `float32`      |



'''

'\n| Use Case                | Data                     | Tensor Type    |\n| ----------------------- | ------------------------ | -------------- |\n| Features/Input          | Continuous values        | `float32`      |\n| Predictions (logits)    | Output from model        | `float32`      |\n| Labels (classification) | Class index (e.g. 0,1,2) | `long` (int64) |\n| Labels (regression)     | Real value (e.g. 4.5)    | `float32`      |\n\n\n\n'

# now training the model

In [33]:
#now defining the training steps
for epoch in range(epochs):
    total_epoch_loss = 0
    
    for feature,label in train_dataloader:
        #loading batch data into gpu
        feature = feature.to(device)
        label = label.to(device)
        #now calling the forward propgation method
        y_pred = model(feature)
        
        #calculating loss function
        loss  =loss_function(y_pred,label)
        
        #now clearing the optimizer object gradient
        optimizer.zero_grad()
        
        
        #now finding out the loss of gradient wrt to parameter by using back propogation algorithm
        loss.backward()
        
        #now updating wts and bias in each layer using optimizer step method
        optimizer.step()
        
        #batch wise loss calculating
        total_epoch_loss = total_epoch_loss+loss.item()
    avg_loss = total_epoch_loss/(len(train_dataloader))
        
    print(f"epochs is :{epoch+1} and loss will be {avg_loss}")
        

epochs is :1 and loss will be 0.9052140907694896
epochs is :2 and loss will be 0.6826502575810688
epochs is :3 and loss will be 0.6504775559529662
epochs is :4 and loss will be 0.6011032694077585
epochs is :5 and loss will be 0.5726148165869138
epochs is :6 and loss will be 0.5407457565772347
epochs is :7 and loss will be 0.5259995293337851
epochs is :8 and loss will be 0.5245088161667809
epochs is :9 and loss will be 0.4961822862368232
epochs is :10 and loss will be 0.49608997940279853
epochs is :11 and loss will be 0.492162199052594
epochs is :12 and loss will be 0.46795279847380394
epochs is :13 and loss will be 0.4610415890017369
epochs is :14 and loss will be 0.46491512284070874
epochs is :15 and loss will be 0.4402229821755706
epochs is :16 and loss will be 0.4595892197889043
epochs is :17 and loss will be 0.441920708308074
epochs is :18 and loss will be 0.43338147092727014
epochs is :19 and loss will be 0.4202950858933036
epochs is :20 and loss will be 0.41185933313681744
epochs

In [34]:
model.linear1.weight

Parameter containing:
tensor([[-0.0137, -0.0297, -0.0652,  ...,  0.8278,  0.4845,  0.2199],
        [ 0.0104,  0.0267,  0.1166,  ..., -0.0101,  0.0362,  0.0794],
        [-0.0029,  0.0233, -0.0314,  ..., -0.0863, -0.0021, -0.0116],
        ...,
        [ 0.0284, -0.0100,  0.0064,  ..., -0.0332, -0.0078, -0.0349],
        [-0.0149,  0.0126,  0.0352,  ..., -0.0826, -0.0383, -0.0501],
        [-0.0316,  0.0341, -0.0869,  ...,  0.0138,  0.0702,  0.0559]],
       device='cuda:0', requires_grad=True)

# evaluating the model

In [35]:
model.eval() #this line we externally added to start evaluation of model

BasicArchitecture(
  (linear1): Linear(in_features=784, out_features=128, bias=True)
  (relu1): ReLU()
  (linear2): Linear(in_features=128, out_features=64, bias=True)
  (relu2): ReLU()
  (linear3): Linear(in_features=64, out_features=10, bias=True)
)

In [36]:
correct = 0
total = 0
with torch.no_grad():
    #passing the test dataset loadr to the model
    for batch_feature,batch_label in testing_dataloader:
        batch_feature = batch_feature.to(device)
        batch_label = batch_label.to(device)
        
        #calling the forward pass
        y_pred = model(batch_feature)
        
        _, predicted = torch.max(y_pred,1) #rtn label wrt to max probability
        
        total = total+batch_label.shape[0]
        
        correct = correct + (predicted==batch_label).sum().item()
        
        
    accuracy = 100 * correct / total
print(f"\n✅ Test Accuracy: {accuracy:.2f}%")


✅ Test Accuracy: 82.00%
