In [1]:
#importing module or library which will be used in this project.
import torch #this library we used to perform tensor computation
import torch.nn as nn
import numpy as np
import pandas as pd
from torch.utils.data import DataLoader,Dataset
from torch.nn.functional import softmax


In [2]:
cleaned_line = []
with open('unstructure.txt','r') as file:
    data = file.read().splitlines()  # list of lines
    #removing empty space between multiple lines.
    for line in data:
        line = line.strip()  # removing whitespace from each line
        if line:  # if line empty nahi hai tabhi add karo
            cleaned_line.append(line)

cleaned_text = "\n".join(cleaned_line)
print(cleaned_text)


About the Program
What is the course fee for  Data Science Mentorship Program (DSMP 2023)
The course follows a monthly subscription model where you have to make monthly payments of Rs 799/month.
What is the total duration of the course?
The total duration of the course is 7 months. So the total course fee becomes 799*7 = Rs 5600(approx.)
What is the syllabus of the mentorship program?
We will be covering the following modules:
Python Fundamentals
Python libraries for Data Science
Data Analysis
SQL for Data Science
Maths for Machine Learning
ML Algorithms
Practical ML
MLOPs
Case studies
You can check the detailed syllabus here - https://learnwith.campusx.in/courses/CampusX-Data-Science-Mentorship-Program-637339afe4b0615a1bbed390
Will Deep Learning and NLP be a part of this program?
No, NLP and Deep Learning both are not a part of this program’s curriculum.
What if I miss a live session? Will I get a recording of the session?
Yes all our sessions are recorded, so even if you miss a sessi

# now applying text preprocessing to textual data changing them into tokens

In [3]:
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [4]:
import re
from nltk.tokenize import word_tokenize
def clean_text(text):
    #before changing the sentence to word tokens first of all we have to do cleaning.
    email_pattern = r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b'
    str_special = r'[^a-zA-Z0-9\s-]'
    url_pattern = r'http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\(\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+'
    html_pattern = r'<[^>]*>.*?</[^>]*>'
    
    #changing the senetence to lower case.
    text = text.lower()
    
    #applying regular expression pattern to sentence.
    text = re.sub(email_pattern,"",text)
    text = re.sub(str_special,"",text)
    text = re.sub(url_pattern,"",text)
    text = re.sub(html_pattern,"",text)
    print(text)
    
    
    lst_word = word_tokenize(text)
    return lst_word

In [5]:
lst_word = clean_text(cleaned_text)
lst_word[:5]

about the program
what is the course fee for  data science mentorship program dsmp 2023
the course follows a monthly subscription model where you have to make monthly payments of rs 799month
what is the total duration of the course
the total duration of the course is 7 months so the total course fee becomes 7997  rs 5600approx
what is the syllabus of the mentorship program
we will be covering the following modules
python fundamentals
python libraries for data science
data analysis
sql for data science
maths for machine learning
ml algorithms
practical ml
mlops
case studies
you can check the detailed syllabus here - httpslearnwithcampusxincoursescampusx-data-science-mentorship-program-637339afe4b0615a1bbed390
will deep learning and nlp be a part of this program
no nlp and deep learning both are not a part of this programs curriculum
what if i miss a live session will i get a recording of the session
yes all our sessions are recorded so even if you miss a session you can go back and watc

['about', 'the', 'program', 'what', 'is']

# building vocubolary based on lst of token we have

In [6]:
#creating empty dictatonary 
vocab = {'<unk>':0}

for word in lst_word:
    if word not in vocab:
        vocab[word] = len(vocab)
vocab

{'<unk>': 0,
 'about': 1,
 'the': 2,
 'program': 3,
 'what': 4,
 'is': 5,
 'course': 6,
 'fee': 7,
 'for': 8,
 'data': 9,
 'science': 10,
 'mentorship': 11,
 'dsmp': 12,
 '2023': 13,
 'follows': 14,
 'a': 15,
 'monthly': 16,
 'subscription': 17,
 'model': 18,
 'where': 19,
 'you': 20,
 'have': 21,
 'to': 22,
 'make': 23,
 'payments': 24,
 'of': 25,
 'rs': 26,
 '799month': 27,
 'total': 28,
 'duration': 29,
 '7': 30,
 'months': 31,
 'so': 32,
 'becomes': 33,
 '7997': 34,
 '5600approx': 35,
 'syllabus': 36,
 'we': 37,
 'will': 38,
 'be': 39,
 'covering': 40,
 'following': 41,
 'modules': 42,
 'python': 43,
 'fundamentals': 44,
 'libraries': 45,
 'analysis': 46,
 'sql': 47,
 'maths': 48,
 'machine': 49,
 'learning': 50,
 'ml': 51,
 'algorithms': 52,
 'practical': 53,
 'mlops': 54,
 'case': 55,
 'studies': 56,
 'can': 57,
 'check': 58,
 'detailed': 59,
 'here': 60,
 '-': 61,
 'httpslearnwithcampusxincoursescampusx-data-science-mentorship-program-637339afe4b0615a1bbed390': 62,
 'deep': 63,


In [7]:
#if i want to show how many no of unique vocobalory present in vocab object.
len(vocab)

273

# based on vocabolary we have build changing the sequential data to integer encoding

In [8]:
def integer_encoding(sentence,vocab):
    text_encoding = []
    sentence = word_tokenize(sentence) #rtn lst of words
    for word in sentence:
        if word in vocab:
            text_encoding.append(vocab[word])
        else:
            text_encoding.append(vocab['<unk>'])
    return text_encoding
    

In [9]:
#now iterating the sentence from cleaned_text and passing them integer_encoding to get integer sequence data.
input_numerical_sentences = []
for line in cleaned_text.split('\n'):
    input_numerical_sentences.append(integer_encoding(line,vocab))


In [10]:
input_numerical_sentences

[[0, 2, 0],
 [0, 5, 2, 6, 7, 8, 0, 0, 0, 0, 0, 0, 13, 0],
 [0, 6, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 16, 24, 25, 0, 0, 0],
 [0, 5, 2, 28, 29, 25, 2, 6, 0],
 [0,
  28,
  29,
  25,
  2,
  6,
  5,
  30,
  31,
  0,
  0,
  2,
  28,
  6,
  7,
  33,
  214,
  0,
  30,
  0,
  0,
  166,
  0,
  0,
  0,
  0],
 [0, 5, 2, 36, 25, 2, 11, 3, 0],
 [0, 38, 39, 40, 2, 41, 42, 0],
 [0, 0],
 [0, 45, 8, 0, 0],
 [0, 0],
 [0, 8, 0, 0],
 [0, 8, 0, 0],
 [0, 0],
 [0, 0],
 [0],
 [0, 56],
 [0, 57, 58, 2, 59, 36, 60, 61, 0, 0, 0],
 [0, 0, 0, 64, 0, 39, 15, 66, 25, 67, 3, 0],
 [0, 0, 0, 64, 0, 0, 69, 70, 71, 15, 66, 25, 67, 3, 0, 0, 73, 0],
 [0, 74, 0, 76, 15, 77, 78, 0, 0, 0, 79, 15, 80, 25, 2, 78, 0],
 [0,
  82,
  83,
  84,
  70,
  85,
  0,
  32,
  86,
  74,
  20,
  76,
  15,
  78,
  20,
  57,
  87,
  88,
  64,
  89,
  2,
  80,
  0],
 [0, 57, 0, 90, 2, 91, 92, 0],
 [0, 67, 94, 95, 22, 96, 97, 98, 97, 99, 100, 25, 2, 6, 61, 0, 0, 0, 0, 0, 0],
 [0, 5, 2, 99, 29, 25, 82, 2, 77, 84, 0],
 [0, 0, 82, 2, 84, 103, 10

In [11]:
#if i want to show max_length of sequential data present in input_numerical_sentences
max_length = max(len(sent) for sent in input_numerical_sentences)
max_length

63

# now applying prepadding to numerical_input_sentence so that all length we get to be same and preparing input and output data

In [12]:
training_seq = []
for sent in input_numerical_sentences:
    for i in range(1,len(sent)):
        training_seq.append(sent[:i+1])

In [13]:
training_seq[:5]

[[0, 2], [0, 2, 0], [0, 5], [0, 5, 2], [0, 5, 2, 6]]

# doing prepadding to training_sequence

In [14]:
#to show the maximum of sequential inputs data.
length_lst = []
for seq in training_seq:
    length_lst.append(len(seq))
max_len = max(length_lst)
max_len
    

63

In [15]:
padded_sequence = []
for seq in training_seq:
    padded_sequence.append([0] * (max_len - len(seq)) + seq)
    

In [16]:
print(padded_sequence[0:5])

[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 2], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 2, 6]]


# padded_sequence object changing them to tensor object

In [17]:
padded_sequence = torch.tensor(padded_sequence,dtype=torch.long)
padded_sequence

tensor([[  0,   0,   0,  ...,   0,   0,   2],
        [  0,   0,   0,  ...,   0,   2,   0],
        [  0,   0,   0,  ...,   0,   0,   5],
        ...,
        [  0,   0,   0,  ...,   0, 160,   0],
        [  0,   0,   0,  ..., 160,   0, 271],
        [  0,   0,   0,  ...,   0, 271, 272]])

# converting unstructure data to supervised data

In [18]:
input_data = padded_sequence[:,:-1]
output_data = padded_sequence[:,-1]

In [19]:
print(output_data)

tensor([  2,   0,   5,   2,   6,   7,   8,   0,   0,   0,   0,   0,   0,  13,
          0,   6,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  16,  24,
         25,   0,   0,   0,   5,   2,  28,  29,  25,   2,   6,   0,  28,  29,
         25,   2,   6,   5,  30,  31,   0,   0,   2,  28,   6,   7,  33, 214,
          0,  30,   0,   0, 166,   0,   0,   0,   0,   5,   2,  36,  25,   2,
         11,   3,   0,  38,  39,  40,   2,  41,  42,   0,   0,  45,   8,   0,
          0,   0,   8,   0,   0,   8,   0,   0,   0,   0,  56,  57,  58,   2,
         59,  36,  60,  61,   0,   0,   0,   0,   0,  64,   0,  39,  15,  66,
         25,  67,   3,   0,   0,   0,  64,   0,   0,  69,  70,  71,  15,  66,
         25,  67,   3,   0,   0,  73,   0,  74,   0,  76,  15,  77,  78,   0,
          0,   0,  79,  15,  80,  25,   2,  78,   0,  82,  83,  84,  70,  85,
          0,  32,  86,  74,  20,  76,  15,  78,  20,  57,  87,  88,  64,  89,
          2,  80,   0,  57,   0,  90,   2,  91,  92,   0,  67,  

# creating custom dataset class

In [20]:
class NextWordDataset(Dataset):
    #constructor method we used to initalize the instance variable.
    def __init__(self,input,output):
        super().__init__()
        self.input = input
        self.output = output
        
    
    def __len__(self):
        return len(self.input)
    
    def __getitem__(self, index):
        #this special method (__getitem__) based on index selecting input and output variable.
        return self.input[index],self.output[index]
  

In [21]:
#creating an object of custom dataset class.
seq_data = NextWordDataset(input_data,output_data)
seq_data

# # using dataloader class we are loading data into batch_size.

In [22]:
#creating an object of dataloader class
seq_dataloader = DataLoader(seq_data,batch_size=32,shuffle=True,pin_memory=True)

In [23]:
#checking how the data will look like after done integer encoding!!!
for question,answer in seq_dataloader:
    print(question)
    print(answer)
    break

tensor([[  0,   0,   0,  ..., 114, 152,   0],
        [  0,   0,   0,  ...,  22, 147, 148],
        [  0,   0,   0,  ...,  71, 134,  22],
        ...,
        [  0,   0,   0,  ...,  64,   0,  39],
        [  0,   0,   0,  ...,  20,  70, 259],
        [  0,   0,   0,  ..., 211,  64,  20]])
tensor([  0,   2,  23, 184,   2, 233,  90,  13,  25,   3, 131,   2,   0,  71,
        181,   0,   0,  15,  94, 164,   2,   0, 119,   0,   0,   2,   0, 248,
          0,  15,  22,  21])


In [24]:
input_data.shape,output_data.shape

(torch.Size([944, 62]), torch.Size([944]))

# # defining neural network architecture

In [25]:
class SimpleLSTM(nn.Module):

    def __init__(self, vocab_size):
        #in this constructor method we are defining the architecture layer of lstm
        super().__init__()
        self.embedding = nn.Embedding(vocab_size, embedding_dim=100)
        self.lstm = nn.LSTM(100,256,batch_first=True) #to get shape will [batch,seq_len,sequ_emb_vector_size]
        self.fc = nn.Linear(256, vocab_size)
    

    def forward(self,input_seq):
        #passing input to defined architecture layer of lstm
            embedded_vector = self.embedding(input_seq)
            intermediate_prev_hidden_state,(final_hidden_state,final_cell_state) = self.lstm(embedded_vector)
            output = self.fc(final_hidden_state.squeeze(0))

            return output

In [26]:
#creating an object of Custom RNN Neural Network Architecture.

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

vocab_size = len(vocab)
model = SimpleLSTM(vocab_size=vocab_size).to(device)
model

SimpleLSTM(
  (embedding): Embedding(273, 100)
  (lstm): LSTM(100, 256, batch_first=True)
  (fc): Linear(in_features=256, out_features=273, bias=True)
)

In [27]:
#if i want to see how many trainable parameter will be train by model
from torchinfo import summary
summary(model=model)

Layer (type:depth-idx)                   Param #
SimpleLSTM                               --
├─Embedding: 1-1                         27,300
├─LSTM: 1-2                              366,592
├─Linear: 1-3                            70,161
Total params: 464,053
Trainable params: 464,053
Non-trainable params: 0

# now defining learning rate epochs and optimizer 

In [28]:
learning_rate = 0.01
optimizers = torch.optim.Adam(model.parameters(),lr=learning_rate,weight_decay=0.001)
#optimizer will update weights and bias in each layer at time of training
epochs = 20

#now defining the loss function for multiclassifer and its inter encode so we are using sparse_categorical cross entropy
loss_fxn = torch.nn.CrossEntropyLoss()
loss_fxn

CrossEntropyLoss()

# now starting the training of model

In [29]:
for epoch in range(epochs):
    model.train()
    training_loss_count = 0
    
    #first we loading the dataset then passing them into neural network architecture.
    for question,answer in seq_dataloader:
        question = question.to(device)
        answer   = answer.to(device)
        
        #passing input sequential to architecture first algo that work is forward pass geenrate the predicted output.
        prediction = model.forward(question) #prediction of output expected in this shape [batch_size,voc_size]
        #but we are getting [batch-size,seq_lenth,voc_size] so thatswhy we have done changes in last_layer.

        
        optimizers.zero_grad()
        
        #calculating the loss value
        losses = loss_fxn(prediction,answer)
        
        losses.backward()
        
        optimizers.step()
        
        training_loss_count = training_loss_count+losses
    print(f"epochs: {epoch+1} and train_loss: {training_loss_count}")
  

epochs: 1 and train_loss: 137.4982147216797
epochs: 2 and train_loss: 107.82183837890625
epochs: 3 and train_loss: 87.28590393066406
epochs: 4 and train_loss: 71.77704620361328
epochs: 5 and train_loss: 58.83515548706055
epochs: 6 and train_loss: 51.1879997253418
epochs: 7 and train_loss: 45.664451599121094
epochs: 8 and train_loss: 39.02388381958008
epochs: 9 and train_loss: 36.217811584472656
epochs: 10 and train_loss: 34.40713119506836
epochs: 11 and train_loss: 31.061033248901367
epochs: 12 and train_loss: 28.91960334777832
epochs: 13 and train_loss: 27.914306640625
epochs: 14 and train_loss: 26.84538459777832
epochs: 15 and train_loss: 24.820310592651367
epochs: 16 and train_loss: 24.597429275512695
epochs: 17 and train_loss: 29.254501342773438
epochs: 18 and train_loss: 27.807222366333008
epochs: 19 and train_loss: 25.218894958496094
epochs: 20 and train_loss: 23.318552017211914


# predicting the model

In [30]:
def prediction(model,vocab,text):
    
    #converting them into integer encoding
    integer_text = integer_encoding(text,vocab)
    
    #padding to text sequence
    padded_text = [0]*(max_length - len(integer_text)) + integer_text
    
    #converting them to tensor object
    padded_tensor = torch.tensor(padded_text,dtype=torch.long).unsqueeze(0).to(device) 
    
    #sending them to model
    logits = model(padded_tensor)
    
    #sending this logits to softmax function
    probs = torch.nn.functional.softmax(logits,dim=1)
    
    value,index = torch.max(probs,1)
    
    #merge with text
    return text + " " + list(vocab.keys())[index]
    
    

In [33]:
prediction(model,vocab,"what is the course fee")

'what is the course fee for'

In [34]:
num_tokens = 20
text = "what is the course fee"
for _ in range(num_tokens):
    next_word = prediction(model, vocab, text)
    print(next_word)
    text = next_word


what is the course fee for
what is the course fee for <unk>
what is the course fee for <unk> <unk>
what is the course fee for <unk> <unk> <unk>
what is the course fee for <unk> <unk> <unk> <unk>
what is the course fee for <unk> <unk> <unk> <unk> <unk>
what is the course fee for <unk> <unk> <unk> <unk> <unk> <unk>
what is the course fee for <unk> <unk> <unk> <unk> <unk> <unk> <unk>
what is the course fee for <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk>
what is the course fee for <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk>
what is the course fee for <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk>
what is the course fee for <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk>
what is the course fee for <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk>
what is the course fee for <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk>
what is the course fee for <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <